version: '3'
services:
  db:
    image: postgres:14.9
    command: postgres -c max_locks_per_transaction=100
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSWORD: dhis
    volumes:
    - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "5432:5432"